version: '3.5'
services:
  lwmail_integrator_c1:
    container_name: migration_service_c1
    build: .
    volumes:
      - .:/opt/globo
    restart: always
    environment:
      - CONTAINER_NUMBER=1
    env_file:
      - .env
  lwmail_integrator_c2:
    container_name: migration_service_c2
    build: .
    volumes:
      - .:/opt/globo
    restart: always
    environment:
      - CONTAINER_NUMBER=2
    env_file:
      - .env
  lwmail_integrator_c3:
    container_name: migration_service_c3
    build: .
    volumes:
      - .:/opt/globo
    restart: always
    environment:
      - CONTAINER_NUMBER=3
    env_file:
      - .env
  lwmail_integrator_c4:
    container_name: migration_service_c4
    build: .
    volumes:
      - .:/opt/globo
    restart: always
    environment:
      - CONTAINER_NUMBER=4
    env_file:
      - .env
  lwmail_integrator_c5:
    container_name: migration_service_c5
    build: .
    volumes:
      - .:/opt/globo
    restart: always
    environment:
      - CONTAINER_NUMBER=5
    env_file:
      - .env