version: '3.5'
services:
  lwmail_integrator_c1:
    container_name: migration_service_c1
    build: .
    volumes:
      - .:/opt/globo
    restart: always
    environment:
      - CONTAINER_NUMBER=1
    env_file:
      - .env
